.PHONY: all
all:
	cd hello;      $(MAKE);
	cd util;       $(MAKE);
	cd sqrattest;  $(MAKE);

.PHONY: install
install:
	cd hello;      $(MAKE) install;
	cd util;       $(MAKE) install;
	cd sqrattest;  $(MAKE) install;

.PHONY: clean
clean:
	cd hello;      $(MAKE) clean;
	cd util;       $(MAKE) clean;
	cd sqrattest;  $(MAKE) clean;
