.PHONY: test
test:
	@echo "---- TEST START ----"
	cd util;        $(MAKE) test;
	cd simple;      $(MAKE) test;
	cd hello;       $(MAKE) test;
	cd sqrattest;   $(MAKE) test;
	cd table1;      $(MAKE) test;
	cd table2;      $(MAKE) test;
	@echo "---- TEST END ----"
